Create Database Triolingo;
Use Triolingo;
-- Table: Users

CREATE TABLE Deutsch_Vocab (
    DID INT PriMARY KEY AUTO_INCREMENT,
    Wort VARCHAR(255) NOT NULL,
    Audio VARCHAR(255) NOT NULL,
    Bild VARCHAR(255) NOT NULL
);
CREATE TABLE Englisch_Vocab (
    EID INT PriMARY KEY AUTO_INCREMENT,
    Wort VARCHAR(255) NOT NULL,
    Audio VARCHAR(255) NOT NULL,
    Bild VARCHAR(255) NOT NULL
);
CREATE TABLE Vocab(
    VID INT PriMARY KEY AUTO_INCREMENT,
    EID INT NOT NULL,
    DID INT NOT NULL,
    EinID INT NOT NULL,
    FOREIGN KEY (EID) REFERENCES Englisch_Vocab(EID),
    FOREIGN KEY (DID) REFERENCES Deutsch_Vocab(DID),
    FOREIGN KEY (EinID) REFERENCES Einheit(EinID)
);
CREATE TABLE Einheit(
    EinID INT PriMARY KEY AUTO_INCREMENT,
    Thema VARCHAR(255) NOT NULL,
    Beschreibung VARCHAR(255) NOT NULL
);

CREATE TABLE Exercise(
    ExID INT PriMARY KEY AUTO_INCREMENT,
    EinID INT NOT NULL,
    Typ VARCHAR(255) NOT NULL,
    FOREIGN KEY (EinID) REFERENCES Einheit(EinID)
);
CREATE TABLE Level(
    LID INT PriMARY KEY AUTO_INCREMENT,
    VID INT NOT NULL,
    UID INT NOT NULL,
    Level INT NOT NULL,
    FOREIGN KEY (VID) REFERENCES Vocab(VID),
    FOREIGN KEY (UID) REFERENCES User(UID)
);

CREATE TABLE User(
    UID INT PriMARY KEY AUTO_INCREMENT,
    Name VARCHAR(255) NOT NULL,
    Passwort VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL
);